  vars:
    nameservers:
      - 8.8.8.8
      - 1.1.1.1

  tasks:
    - name: Configure resolver
      ansible.builtin.template:
        src: templates/etc_resolv.conf.j2
        dest: /etc/resolv.conf
        group: root
        owner: root
        mode: 0644